### ISSUE TITLE
Should be clear that we don't intend students to clone down this repo to open a index.ipynb file

### ISSUE THREAD

**Issue by lindseyberlin** [learn-co-curriculum/dsc-running-jupyter-locally#1]
Students often do these steps to clone down this repository onto their local, but get confused at the last step because there isn't an index.ipynb file in this repository. We should be more explicit that these instructions are for other code lessons/labs, and potentially point a student towards a specific one where they can follow these steps

**Comment by bpurdy-ds** [comment]
This is completed. Closed with commit: https://github.com/learn-co-curriculum/dsc-running-jupyter-locally/issues/1#issue-712129909
