### ISSUE TITLE
No index.ipynb file

### ISSUE THREAD

**Issue by dan-rl1976** [learn-co-curriculum/dsc-running-jupyter-locally#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4339/pages/running-jupyter-notebooks-locally?module_item_id=276033

## What should be changed?

"Then click on the index.ipynb file which is the Jupyter Notebook we will be using in this and future labs and lessons. This will open a new tab where you will see the same content you saw in IllumiDesk on Canvas!"

From the "Starting Jupyter Notebook" section, instructs you to "click on the index.ipynb" file but there is no such file in the directory that I can find. I only see:

(folder) images
Contributing.md
license.md
readme.md

**Comment by bpurdy-ds** [comment]
There is not supposed to be a .index file. We need to make this clear in the directions. I'll close this one, and the solution will be found [here](https://github.com/learn-co-curriculum/dsc-running-jupyter-locally/issues/1).
