### ISSUE TITLE
Running Jupyter Notebooks Locally: Data Science Prep error

### ISSUE THREAD

**Issue by rbdaly16** [learn-co-curriculum/dsc-running-jupyter-locally#3]
## Link to Canvas

https://learning.flatironschool.com/courses/6793/pages/running-jupyter-notebooks-locally?module_item_id=543623

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x ] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue
In the section, Starting the Jupyter Notebook, it says "Make sure to activate your conda virtual environment in your terminal first by typing source activate learn-env". I tried this and it didn't work. I then instead typed conda activate learn-env and it did work. I believe source should be replaced by conda.
### Source

Make sure to activate your conda virtual environment in your terminal first by typing source activate learn-env```

```

### Concern
<!-- Below this line, describe why this code or markdown is causing an issue.
Include screenshots if applicable -->


## (Optional) Proposed Solution
<!-- If you have a suggestion for alternative code or markdown that would resolve
your issue, provide that below -->
I believe source should be replaced by conda.

## What OS Are You Using?

- [x ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

## Any Additional Context?
<!-- Add any other context about the problem here. -->

**Comment by jessepisel** [comment]
Thanks for opening this issue 👋 with us. I have updated the page so the instructions use the modern `conda activate` rather than the old `source activate` with commit [49aa00d](https://github.com/learn-co-curriculum/dsc-running-jupyter-locally/commit/49aa00d69cf49a0f54b0379110891d61967a2e98). I am closing this issue at this time.
